Repository kubeedge/examples, pull requests merged in 2021-01, with the labels that each got.

#75 Corrected some format, grammar and spelling errors
  kubeedge-edge-ai-application/README.md
Labels: approved, lgtm, size/M

#76 demo: update bluetooth-CC2650-demo
  bluetooth-CC2650-demo/README.md
  bluetooth-CC2650-demo/crds/CC2650-device-instance.yaml
  bluetooth-CC2650-demo/crds/CC2650-device-model.yaml
Labels: approved, lgtm, size/S

#78 demo: update ai demo prerequisites
  kubeedge-edge-ai-application/README.md
Labels: approved, lgtm, size/XS
